### ISSUE TITLE
ToSocketAddrs

### ISSUE THREAD

**Issue by conradev** [dimbleby/ip-rs#2]
Is there any way to implement `ToSocketAddrs` for `(IpAddr, u16)`, like it is [in std](https://github.com/rust-lang/rust/blob/7a7307e5cf08ad25de62d4f9e13ddd58c59881c8/src/libstd/net/addr.rs#L363-L372)?

It doesn't seem to be possible because even though `IpAddr` is declared in `lib.rs`, `rustc` figures that `(IpAddr, u16)` isn't declared in the crate.

**Comment by dimbleby** [comment]
I believe you are correct that this is not possible, for the reason that you give.

You can easily get a `SocketAddr` from an `(IpAddr, u16)` pair via the `SocketAddrExt` trait, and I'd guess that's probably the simplest and best thing to do.

However, if you've some really excellent use case for the `ToSocketAddrs` trait, I guess that we could introduce a new `ToSocketAddrsExt` trait such that:
- definition is same as `ToSocketAddrs`
- it inherits the `ToSocketAddrs` implementation for objects with that trait
- it adds its own implementation for `(IpAddr, u16)` pairs

But this feels a little awkward and I'm not entirely convinced of the usefulness.

What do you think?

**Comment by dimbleby** [comment]
Actually I think that even that exact plan doesn't work - the compiler will complain that implementations `impl<T: ToSocketAddrs> ToSocketAddrsExt for T` and `impl ToSocketAddrsExt for (IpAddr, u16)` conflict.  (Even though they don't!  But if I understand correctly, the compiler assumes that one day they _might_).

Therefore, to get a trait that behaves as a superset of `ToSocketAddrs` we'd have to spell out the full implementation for all types here, which I'm not at all enthusiastic about.

**Comment by conradev** [comment]
Yeah, totally, that would be annoying.

The reason it would be great would be to have the ability to pass an `IpAddr` directly to `TcpStream::connect`, but using `SocketAddrExt` isn't awful.
